server:
  port: 8003
spring:
  application:
    name: consul-server
  cloud:
    consul:
      host: localhost #consul服务的地址
      port: 8500   #默认的端口号
      discovery:
        hostname: 192.168.92.188 #将服务别名获取的地址直接映射成ip地址